### ISSUE TITLE
Yurii Smazhnyi

### ISSUE THREAD

**Issue by McMuzil** [oleksandr-medviediev/campus_2018_python#1]
Not sure they are solved in best way.

[Tasks.zip](https://github.com/oleksandr-medviediev/campus_2018_python/files/2496554/Tasks.zip)

**Comment by oleksandr-medviediev** [comment]
> Not sure they are solved in best way.
> 
> [Tasks.zip](https://github.com/oleksandr-medviediev/campus_2018_python/files/2496554/Tasks.zip)

Please, add everything to a new folder named as FirstName_LastName and push it to the repo within a new branch. Thanks.
